version: '3'

services:
  refbot:
    container_name: 'refbot'
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:5000"
    expose:
      - "5000"
