version: '3'

services:
  refbot:
    container_name: 'refbot'
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn getref_bot:app --bind 0.0.0.0:$PORT --reload
    env_file:
      - .env
    ports:
      - "8000:${PORT}"
    expose:
      - "${PORT}"
